### ISSUE TITLE
Loading Indicator In Safari

### ISSUE THREAD

**Issue by shaundon** [maxpowel/jQuery-XMPP-plugin#10] opened 2012-07-23 22:37 UTC
When using the plugin on a page, upon signing in the spinning wheel page loading indicator remains on screen persistently until the connection times out. I've tested in Chrome and Firefox (both on OS X) and it doesn't happen there. Is there a way to prevent this?

**Comment by maxpowel** [comment] 2012-07-25 14:22
its probably caused by the ajax connection. For the web browser its a normal request (like get an image) and because of that safari thinks that the page is not loaded.

When you do other ajax requests this spinning wheels appears?

**Comment by shaundon** [comment] 2012-07-26 10:21
I've looked into it a little more and it does appear to be a feature of Safari, so it's unlikely to be fixable

**Comment by maxpowel** [comment] 2012-07-29 12:17
I close this issue since the problem is outside of the library

**Closed as completed by maxpowel** 2012-07-29 12:17 UTC

**Comment by shaundon** [comment] 2012-07-30 10:09
Thanks
